import logictensornetworks as ltn
import numpy as np

number_of_features = 30

#identity matrix 30 * 30
features_for_generic_peoples = np.identity(number_of_features).tolist()
person = ltn.Domain_union([ltn.Constant("p"+str(i), features_for_generic_peoples[i]) for i in range(number_of_features)])

everybody = []

male = ltn.Constant("male", domain=person)
everybody.append(male)
female = ltn.Constant("female", domain=person)
everybody.append(female)
g_r_s_mead = ltn.Constant("g_r_s_mead", domain=person)
everybody.append(g_r_s_mead)
ismael_valenzuela = ltn.Constant("ismael_valenzuela", domain=person)
everybody.append(ismael_valenzuela)
vincent_de_paul = ltn.Constant("vincent_de_paul", domain=person)
everybody.append(vincent_de_paul)
claude_delvincourt = ltn.Constant("claude_delvincourt", domain=person)
everybody.append(claude_delvincourt)
pierre_jeanneret = ltn.Constant("pierre_jeanneret", domain=person)
everybody.append(pierre_jeanneret)
jack_barry = ltn.Constant("jack_barry", domain=person)
everybody.append(jack_barry)
southbridge = ltn.Constant("southbridge", domain=person)
everybody.append(southbridge)
bartolomeo_pagano = ltn.Constant("bartolomeo_pagano", domain=person)
everybody.append(bartolomeo_pagano)
peter_russell_1733 = ltn.Constant("peter_russell_1733", domain=person)
everybody.append(peter_russell_1733)
sewickley = ltn.Constant("sewickley", domain=person)
everybody.append(sewickley)
wilhelm_von_tegetthoff = ltn.Constant("wilhelm_von_tegetthoff", domain=person)
everybody.append(wilhelm_von_tegetthoff)
evadne_price = ltn.Constant("evadne_price", domain=person)
everybody.append(evadne_price)
hanging = ltn.Constant("hanging", domain=person)
everybody.append(hanging)
sam_barkas = ltn.Constant("sam_barkas", domain=person)
everybody.append(sam_barkas)
jessie_matthews = ltn.Constant("jessie_matthews", domain=person)
everybody.append(jessie_matthews)
kalmar = ltn.Constant("kalmar", domain=person)
everybody.append(kalmar)
dan_ii_of_wallachia = ltn.Constant("dan_ii_of_wallachia", domain=person)
everybody.append(dan_ii_of_wallachia)
martin_ritt = ltn.Constant("martin_ritt", domain=person)
everybody.append(martin_ritt)
patience_cooper = ltn.Constant("patience_cooper", domain=person)
everybody.append(patience_cooper)
chester_carlson = ltn.Constant("chester_carlson", domain=person)
everybody.append(chester_carlson)
marie_anne_mancini = ltn.Constant("marie_anne_mancini", domain=person)
everybody.append(marie_anne_mancini)
jacques_duke_of_savoy = ltn.Constant("jacques_duke_of_savoy", domain=person)
everybody.append(jacques_duke_of_savoy)
richard_leech = ltn.Constant("richard_leech", domain=person)
everybody.append(richard_leech)
niccolo_paganini = ltn.Constant("niccolo_paganini", domain=person)
everybody.append(niccolo_paganini)
helen_chadwick = ltn.Constant("helen_chadwick", domain=person)
everybody.append(helen_chadwick)

roman_catholic_church = ltn.Constant("roman_catholic_church", domain=person)
everybody.append(roman_catholic_church)
catholicism = ltn.Constant("catholicism", domain=person)
everybody.append(catholicism)

artist = ltn.Constant("artist", domain=person)
everybody.append(artist)
violinist = ltn.Constant("violinist", domain=person)
everybody.append(violinist)
physicist = ltn.Constant("physicist", domain=person)
everybody.append(physicist)
actor = ltn.Constant("actor", domain=person)
everybody.append(actor)
scientist = ltn.Constant("scientist", domain=person)
everybody.append(scientist)
playwright = ltn.Constant("playwright", domain=person)
everybody.append(playwright)
baseball_player = ltn.Constant("baseball_player", domain=person)
everybody.append(baseball_player)