import logictensornetworks as ltn
import numpy as np

number_of_features = 30
#identity matrix 30 * 30
features_for_generic_peoples = np.identity(number_of_features).tolist()
person = ltn.Domain_union([ltn.Constant("p"+str(i), features_for_generic_peoples[i]) for i in range(number_of_features)])
everybody = []
first_group = []
second_group = []

charles_ii_grand_duke_of_mecklenburg_strelitz = ltn.Constant("charles_ii_grand_duke_of_mecklenburg_strelitz", domain=person)
first_group.append(charles_ii_grand_duke_of_mecklenburg_strelitz)
lady_frances_brandon = ltn.Constant("lady_frances_brandon", domain=person)
first_group.append(lady_frances_brandon)
henry_herbert_2nd_earl_of_pembroke = ltn.Constant("henry_herbert_2nd_earl_of_pembroke", domain=person)
first_group.append(henry_herbert_2nd_earl_of_pembroke)
julia_the_elder = ltn.Constant("julia_the_elder", domain=person)
first_group.append(julia_the_elder)
gaius_octavius = ltn.Constant("gaius_octavius", domain=person)
first_group.append(gaius_octavius)
friederike_of_hesse_darmstadt = ltn.Constant("friederike_of_hesse_darmstadt", domain=person)
first_group.append(friederike_of_hesse_darmstadt)
livia = ltn.Constant("livia", domain=person)
first_group.append(livia)
early_life_of_augustus = ltn.Constant("early_life_of_augustus", domain=person)
first_group.append(early_life_of_augustus)
george_v_of_hanover = ltn.Constant("george_v_of_hanover", domain=person)
first_group.append(george_v_of_hanover)
scribonia = ltn.Constant("scribonia", domain=person)
first_group.append(scribonia)
lady_catherine_grey = ltn.Constant("lady_catherine_grey", domain=person)
first_group.append(lady_catherine_grey)
ernest_augustus_i_of_hanover = ltn.Constant("ernest_augustus_i_of_hanover", domain=person)
first_group.append(ernest_augustus_i_of_hanover)
george_hearst = ltn.Constant("george_hearst", domain=person)
first_group.append(george_hearst)
julius_caesar = ltn.Constant("julius_caesar", domain=person)
first_group.append(julius_caesar)
william_randolph_hearst = ltn.Constant("william_randolph_hearst", domain=person)
first_group.append(william_randolph_hearst)
clodia_pulchra = ltn.Constant("clodia_pulchra", domain=person)
first_group.append(clodia_pulchra)
phoebe_hearst = ltn.Constant("phoebe_hearst", domain=person)
first_group.append(phoebe_hearst)
prince_louis_charles_of_prussia = ltn.Constant("prince_louis_charles_of_prussia", domain=person)
first_group.append(prince_louis_charles_of_prussia)
atia = ltn.Constant("atia", domain=person)
first_group.append(atia)
frederica_of_mecklenburg_strelitz = ltn.Constant("frederica_of_mecklenburg_strelitz", domain=person)
first_group.append(frederica_of_mecklenburg_strelitz)
elisabeth_i_of_bohemia = ltn.Constant("elisabeth_i_of_bohemia", domain=person)
second_group.append(elisabeth_i_of_bohemia)
raymond_iii_of_tripoli = ltn.Constant("raymond_iii_of_tripoli", domain=person)
second_group.append(raymond_iii_of_tripoli)
princess_viktoria_of_prussia = ltn.Constant("princess_viktoria_of_prussia", domain=person)
second_group.append(princess_viktoria_of_prussia)
elizabeth_boleyn_countess_of_wiltshire = ltn.Constant("elizabeth_boleyn_countess_of_wiltshire", domain=person)
second_group.append(elizabeth_boleyn_countess_of_wiltshire)
dorothy_ayer_gardner_ford = ltn.Constant("dorothy_ayer_gardner_ford", domain=person)
second_group.append(dorothy_ayer_gardner_ford)
albert_of_saxe_coburg_and_gotha = ltn.Constant("albert_of_saxe_coburg_and_gotha", domain=person)
second_group.append(albert_of_saxe_coburg_and_gotha)
victoria_princess_royal = ltn.Constant("victoria_princess_royal", domain=person)
second_group.append(victoria_princess_royal)
princess_margaret_of_prussia = ltn.Constant("princess_margaret_of_prussia", domain=person)
second_group.append(princess_margaret_of_prussia)
plectrude = ltn.Constant("plectrude", domain=person)
second_group.append(plectrude)
charles_v_of_france = ltn.Constant("charles_v_of_france", domain=person)
second_group.append(charles_v_of_france)
pippin_of_herstal = ltn.Constant("pippin_of_herstal", domain=person)
second_group.append(pippin_of_herstal)
bonne_of_bohemia = ltn.Constant("bonne_of_bohemia", domain=person)
second_group.append(bonne_of_bohemia)
prince_sigismund_of_prussia = ltn.Constant("prince_sigismund_of_prussia", domain=person)
second_group.append(prince_sigismund_of_prussia)
hodierna_of_tripoli = ltn.Constant("hodierna_of_tripoli", domain=person)
second_group.append(hodierna_of_tripoli)
elizabeth_tilney = ltn.Constant("elizabeth_tilney", domain=person)
second_group.append(elizabeth_tilney)
john_ii_of_france = ltn.Constant("john_ii_of_france", domain=person)
second_group.append(john_ii_of_france)
prince_waldemar_of_prussia = ltn.Constant("prince_waldemar_of_prussia", domain=person)
second_group.append(prince_waldemar_of_prussia)
louis_i_of_naples = ltn.Constant("louis_i_of_naples", domain=person)
second_group.append(louis_i_of_naples)
thomas_howard_3rd_duke_of_norfolk = ltn.Constant("thomas_howard_3rd_duke_of_norfolk", domain=person)
second_group.append(thomas_howard_3rd_duke_of_norfolk)
baldwin_ii_of_jerusalem = ltn.Constant("baldwin_ii_of_jerusalem", domain=person)
second_group.append(baldwin_ii_of_jerusalem)
philip_ii_duke_of_burgundy = ltn.Constant("philip_ii_duke_of_burgundy", domain=person)
second_group.append(philip_ii_duke_of_burgundy)
prince_heinrich_of_prussia = ltn.Constant("prince_heinrich_of_prussia", domain=person)
second_group.append(prince_heinrich_of_prussia)
drogo_of_champagne = ltn.Constant("drogo_of_champagne", domain=person)
second_group.append(drogo_of_champagne)
gerald_ford = ltn.Constant("gerald_ford", domain=person)
second_group.append(gerald_ford)
raymond_ii_of_tripoli = ltn.Constant("raymond_ii_of_tripoli", domain=person)
second_group.append(raymond_ii_of_tripoli)
sophia_of_prussia = ltn.Constant("sophia_of_prussia", domain=person)
second_group.append(sophia_of_prussia)
frederick_iii_german_emperor = ltn.Constant("frederick_iii_german_emperor", domain=person)
second_group.append(frederick_iii_german_emperor)
thomas_howard_2nd_duke_of_norfolk = ltn.Constant("thomas_howard_2nd_duke_of_norfolk", domain=person)
second_group.append(thomas_howard_2nd_duke_of_norfolk)
gerald_rudolff_ford = ltn.Constant("gerald_rudolff_ford", domain=person)
second_group.append(gerald_rudolff_ford)
william_ii_german_emperor = ltn.Constant("william_ii_german_emperor", domain=person)
second_group.append(william_ii_german_emperor)
princess_charlotte_of_prussia = ltn.Constant("princess_charlotte_of_prussia", domain=person)
second_group.append(princess_charlotte_of_prussia)
victoria_of_the_united_kingdom = ltn.Constant("victoria_of_the_united_kingdom", domain=person)
second_group.append(victoria_of_the_united_kingdom)
